version: '3.8'

services:
  api:
    build: .
    container_name: math-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - .:/app
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  streamlit:
    build:
      context: ./streamlit-ui
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./streamlit-ui:/app
